{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "PkbkbMxVrGiL",
        "outputId": "b43039c0-538e-4bfb-db9e-56e90b15ad2c"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "IDPasien\t|Nama Pasien\t|Jenis Kelamin\t| Usia Pasien\t| Penyakit\t| Poli\t\t| Biaya Pengobatan\n",
            "1\t\t|Gerry\t\t|Pria\t\t| 25\t\t| Maag\t\t| SpPD\t\t| 170000\t\n",
            "2\t\t|Ghina\t\t|Wanita\t\t| 5\t\t| Demam\t\t| SpA\t\t| 150000\t\n",
            "3\t\t|Fira\t\t|Wanita\t\t| 18\t\t| Flu\t\t| Umum\t\t| 100000\t\n",
            "IDPasien\t|Nama Pasien\t|Jenis Kelamin\t| Usia Pasien\t| Penyakit\t| Poli\t\t| Biaya Pengobatan\n",
            "1\t\t|Gerry\t\t|Pria\t\t| 25\t\t| Maag\t\t| SpPD\t\t| 170000\t\n",
            "Daftar Biaya Pengobatan: \n",
            "IDPasien\t|Nama Pasien\t|Jenis Kelamin\t| Usia Pasien\t| Penyakit\t| Poli\t\t| Biaya Pengobatan\n",
            "1\t\t|Gerry\t\t|Pria\t\t| 25\t\t| Maag\t\t| SpPD\t\t| 170000\t\n",
            "Total Yang Harus Dibayar = Rp.170000\n",
            "Terima kasih poi\n",
            "IDPasien\t|Nama Pasien\t|Jenis Kelamin\t| Usia Pasien\t| Penyakit\t| Poli\t\t| Biaya Pengobatan\n",
            "2\t\t|Ghina\t\t|Wanita\t\t| 5\t\t| Demam\t\t| SpA\t\t| 150000\t\n",
            "3\t\t|Fira\t\t|Wanita\t\t| 18\t\t| Flu\t\t| Umum\t\t| 100000\t\n"
          ]
        }
      ],
      "source": [
        "import math as m\n",
        "ListPasienRumahSakit = [\n",
        "    {\n",
        "        \"IDPasien\" : 1,\n",
        "        \"Nama Pasien\" : \"Gerry\",\n",
        "        \"Usia Pasien\" : 25,\n",
        "        \"Jenis Kelamin\" : \"Pria\",\n",
        "        \"Penyakit\" : \"Maag\",\n",
        "        \"Poli\" : \"SpPD\",\n",
        "        \"Biaya Pengobatan\" : 170000,  \n",
        "    },\n",
        "    {\n",
        "        \"IDPasien\" : 2,\n",
        "        \"Nama Pasien\" : \"Ghina\",\n",
        "        \"Usia Pasien\" : 5,\n",
        "        \"Jenis Kelamin\" : \"Wanita\",\n",
        "        \"Penyakit\" : \"Demam\",\n",
        "        \"Poli\" : \"SpA\",\n",
        "        \"Biaya Pengobatan\" : 150000,  \n",
        "    },\n",
        "    {\n",
        "        \"IDPasien\" : 3,\n",
        "        \"Nama Pasien\" : \"Fira\",\n",
        "        \"Usia Pasien\" : 18,\n",
        "        \"Jenis Kelamin\" : \"Wanita\",\n",
        "        \"Penyakit\" : \"Flu\",\n",
        "        \"Poli\" : \"Umum\",\n",
        "        \"Biaya Pengobatan\" : 100000,\n",
        "    }\n",
        "]\n",
        "\n",
        "# Fungsi List Semua Database\n",
        "def TampilkanListSemuaDataPasien() :\n",
        "    if len(ListPasienRumahSakit)==0 :\n",
        "        print(\"Tidak Ada List Data Pasien\")\n",
        "    else:\n",
        "        print('IDPasien\\t|Nama Pasien\\t|Jenis Kelamin\\t| Usia Pasien\\t| Penyakit\\t| Poli\\t\\t| Biaya Pengobatan')\n",
        "        for i in range(len(ListPasienRumahSakit)):\n",
        "            print('{}\\t\\t|{}\\t\\t|{}\\t\\t| {}\\t\\t| {}\\t\\t| {}\\t\\t| {}\\t'.format(ListPasienRumahSakit[i].get('IDPasien'),ListPasienRumahSakit[i].get('Nama Pasien'),ListPasienRumahSakit[i].get('Jenis Kelamin'),ListPasienRumahSakit[i].get('Usia Pasien'),ListPasienRumahSakit[i].get('Penyakit'),ListPasienRumahSakit[i].get('Poli'),ListPasienRumahSakit[i].get('Biaya Pengobatan')))\n",
        "\n",
        "#Menu Read Data\n",
        "def MenampilkanListPasienRumahSakit() :\n",
        "    while True:\n",
        "        PilihanMenuRead = int(input('''\n",
        "        List Data Pasien Rumah Sakit Brawijaya\n",
        "        \n",
        "        1. Data Seluruh Pasien\n",
        "        2. Filter Pencarian Data Pasien Tertentu\n",
        "        3. Kembali ke Menu Utama\n",
        "        \n",
        "        Silahkan Masukkan Pilihan Menu Read Data Pasien : '''))\n",
        "        if PilihanMenuRead == 1:\n",
        "            if len(ListPasienRumahSakit)==0 :\n",
        "                print(\"Tidak Ada List Data Pasien\")\n",
        "            else:\n",
        "                TampilkanListSemuaDataPasien()\n",
        "        elif PilihanMenuRead == 2:\n",
        "            IDPasien = int(input(\"Masukkan IDPasien: \"))\n",
        "            print()\n",
        "            while True: \n",
        "                for i in range(len(ListPasienRumahSakit)):\n",
        "                    if IDPasien == ListPasienRumahSakit[i].get('IDPasien'):\n",
        "                        print('IDPasien\\t|Nama Pasien\\t|Jenis Kelamin\\t| Usia Pasien\\t| Penyakit\\t| Poli\\t\\t| Biaya Pengobatan')\n",
        "                        print('{}\\t\\t|{}\\t\\t|{}\\t\\t| {}\\t\\t| {}\\t\\t| {}\\t\\t| {}\\t'.format(ListPasienRumahSakit[i].get('IDPasien'),ListPasienRumahSakit[i].get('Nama Pasien'),ListPasienRumahSakit[i].get('Jenis Kelamin'),ListPasienRumahSakit[i].get('Usia Pasien'),ListPasienRumahSakit[i].get('Penyakit'),ListPasienRumahSakit[i].get('Poli'),ListPasienRumahSakit[i].get('Biaya Pengobatan')))\n",
        "                        break\n",
        "                    elif i == len(ListPasienRumahSakit):\n",
        "                        print(\"Maaf ID Pasien Tidak Ada\")\n",
        "                        break\n",
        "                break\n",
        "        elif PilihanMenuRead == 3:\n",
        "            Back = input(\"Apakah Anda Ingin Kembali ke Menu Utama? (Y/N) : \")\n",
        "            Back = Back.upper()\n",
        "            if Back == 'Y':\n",
        "                break\n",
        "            elif Back == 'N':\n",
        "                continue\n",
        "            else:\n",
        "                print(\"Silahkan Ketik 'Y' Jika Ingin Kembali ke Menu Utama atau Ketik 'N' Jika Ingin Menggagalkan\")\n",
        "                continue\n",
        "        else:\n",
        "            print(\"Maaf, Menu yang Anda pilih tidak tersedia. Silahkan Memilih Menu yang lain\")\n",
        "        \n",
        "#Menu Create Data\n",
        "def MenambahkanDataPasienRumahSakit() :\n",
        "    while True:\n",
        "        pilihanMenambahkanPasien = int(input('''\n",
        "        Menambahkan Data Pasien Rumah Sakit Brawijaya\n",
        "        \n",
        "        1. Menambah Data Pasien Baru \n",
        "        2. Kembali ke Menu Utama\n",
        "        \n",
        "        Silahkan Masukkan Pilihan Menu : '''))\n",
        "        print()\n",
        "        if pilihanMenambahkanPasien == 1:\n",
        "            IDPasien = int(input('''\n",
        "            Silahkan Masukkan ID Pasien : '''))\n",
        "            print()\n",
        "            if isUniqueId(IDPasien):\n",
        "                NamaPasien = input(\"Masukkan Nama Pasien : \")\n",
        "                UsiaPasien = int(input(\"Masukkan Usia Pasien : \"))\n",
        "                JenisKelamin = input(\"Masukkan Jenis Kelamin Pasien : \")\n",
        "                Penyakit = input(\"Masukkan Penyakit Yang Dialami : \")\n",
        "                Poli = input(\"Masukkan Poli Yang Dikunjungi : \")\n",
        "                BiayaPengobatan = int(input(\"Masukkan Biaya Pengobatan : \"))\n",
        "                MenambahData = input(\"Apakah Anda Yakin Ingin Menambah Data Ini? (Y/N) : \")\n",
        "                print()\n",
        "                if MenambahData.casefold() == 'Y'.casefold():\n",
        "                    print(\"Data Berhasil Disimpan\")\n",
        "                    ListPasienRumahSakit.append({\"IDPasien\": IDPasien,\"Nama Pasien\": NamaPasien,\"Usia Pasien\": UsiaPasien,\"Jenis Kelamin\": JenisKelamin,\"Penyakit\": Penyakit,\"Poli\": Poli,\"Biaya Pengobatan\": BiayaPengobatan})\n",
        "                    TampilkanListSemuaDataPasien()\n",
        "                    break\n",
        "                elif MenambahData.casefold() == 'N'.casefold():\n",
        "                    print(\"Data Gagal Disimpan\")\n",
        "                    break\n",
        "                else:\n",
        "                    print(\"Menu yang Anda masukkan tidak ada. Silahkan ketik 'Y' jika ingin data disimpan atau 'N' jika tidak ingin data disimpan\")\n",
        "                    break\n",
        "            else:\n",
        "                print(\"Tidak Dapat Menambah Daftar Pasien Karena ID Tersebut Sudah Ada\")\n",
        "                break\n",
        "        elif pilihanMenambahkanPasien == 2:\n",
        "            Back = input(\"Apakah Anda Ingin Kembali ke Menu Utama? (Y/N) : \")\n",
        "            if Back.casefold() == 'Y'.casefold():\n",
        "                break\n",
        "            elif Back.casefold() == 'N'.casefold():\n",
        "                continue\n",
        "            else:\n",
        "                print(\"Silahkan Ketik 'Y' Jika Ingin Kembali ke Menu Utama atau Ketik 'N' Jika Ingin Menggagalkan\")\n",
        "                continue\n",
        "        else:\n",
        "            print(\"Maaf, Menu yang Anda pilih tidak tersedia. Silahkan Memilih Menu yang lain\")\n",
        "\n",
        "#Menu Update Data\n",
        "def MengubahDataPasien():\n",
        "    while True:\n",
        "        PilihanMengubahData = int(input('''\n",
        "        Mengubah Data Pasien Rumah Sakit Brawijaya\n",
        "        \n",
        "        1. Mengubah Data Pasien\n",
        "        2. Kembali ke Menu Utama\n",
        "        \n",
        "        Silahkan Masukkan Pilihan Menu : '''))\n",
        "       \n",
        "        if PilihanMengubahData == 1:\n",
        "            IDPasien = int(input(\"Masukkan ID Pasien : \"))\n",
        "            print()\n",
        "            for i in range(len(ListPasienRumahSakit)):\n",
        "                if IDPasien == ListPasienRumahSakit[i].get(\"IDPasien\"):\n",
        "                    print('IDPasien\\t|Nama Pasien\\t|Jenis Kelamin\\t| Usia Pasien\\t| Penyakit\\t| Poli\\t\\t| Biaya Pengobatan')\n",
        "                    print('{}\\t\\t|{}\\t\\t|{}\\t\\t| {}\\t\\t| {}\\t\\t| {}\\t\\t| {}\\t'.format(ListPasienRumahSakit[i].get('IDPasien'),ListPasienRumahSakit[i].get('Nama Pasien'),ListPasienRumahSakit[i].get('Jenis Kelamin'),ListPasienRumahSakit[i].get('Usia Pasien'),ListPasienRumahSakit[i].get('Penyakit'),ListPasienRumahSakit[i].get('Poli'),ListPasienRumahSakit[i].get('Biaya Pengobatan')))\n",
        "                    YakinMengubahData = input(\"Apakah Anda Yakin Ingin Mengubah Data Pasien? (Y/N)\")\n",
        "                    YakinMengubahData = YakinMengubahData.upper()\n",
        "                    print()\n",
        "                    if YakinMengubahData == 'Y':\n",
        "                        Data = input(\"Masukkan Data Pasien Yang Ingin Diubah\")\n",
        "                        Data = Data.strip().lower()\n",
        "                        if Data == 'IDPasien'.casefold():\n",
        "                            print(\"Maaf, ID Pasien Tidak Dapat Diubah\")\n",
        "                            break\n",
        "                        elif Data in list({k.strip().lower(): v for k, v in ListPasienRumahSakit[i].items()}):\n",
        "                            newValue = input(f\"Masukkan {Data} baru : \")\n",
        "                            YakinMengubahData2 = input(f\"Apakah Anda Yakin Ingin Mengubah Data {Data}'? (Y/N)\")\n",
        "                            YakinMengubahData2 = YakinMengubahData2.upper()\n",
        "                            if YakinMengubahData2 == \"Y\":\n",
        "                                UpdateData(Data, i, newValue)\n",
        "                                print()\n",
        "                                print(f\"Data '{Data}' berhasil diubah dan disimpan\")\n",
        "                                break\n",
        "                            elif YakinMengubahData2 == \"N\":\n",
        "                                print(f\"Data {Data} tidak jadi diubah\")\n",
        "                                break\n",
        "                            else:\n",
        "                                print(\"Silahkan Ketik 'Y' Jika Ingin Menyimpan Data Yang Telah Diubah atau 'N' Jika Ingin Membatalkan Mengubah Data Pasien\")\n",
        "                                break\n",
        "                        else:\n",
        "                            print(f\"Maaf Data '{Data}' Tidak Ada\")\n",
        "                            break\n",
        "                    elif YakinMengubahData == 'N':\n",
        "                        print(\"Data Pasien Tidak Jadi Diubah\")\n",
        "                        break\n",
        "                    else:\n",
        "                        print(\"Silahkan Ketik 'Y' Jika Ingin Mengubah Data Pasien atau 'N' Jika Ingin Membatalkan Mengubah Data Pasien\")\n",
        "                        break\n",
        "\n",
        "                elif i == len(ListPasienRumahSakit):\n",
        "                    print(\"Maaf ID Pasien Tidak Ada\")\n",
        "                    break\n",
        "        elif PilihanMengubahData == 2:\n",
        "            inginKembali = input(\"Apakah Anda Ingin Kembali ke Menu Utama? (Y/N) : \")\n",
        "            if inginKembali.casefold() == 'Y'.casefold():\n",
        "                break\n",
        "            elif inginKembali.casefold() == 'N'.casefold():\n",
        "                continue\n",
        "            else:\n",
        "                print(\"Silahkan Ketik 'Y' Jika Ingin Kembali ke Menu Utama atau Ketik 'N' Jika Ingin Tetap di Menu Mengubah Data Pasien\")\n",
        "                continue\n",
        "        else:\n",
        "            print(\"Maaf, Menu yang Anda pilih tidak tersedia. Silahkan Memilih Menu yang lain\")\n",
        "\n",
        "#Menu Delete Data\n",
        "def MenghapusDataPasien():\n",
        "    while True:\n",
        "        pilihanMenghapusData = int(input('''\n",
        "        Menghapus Data Pasien Rumah Sakit Brawijaya\n",
        "        \n",
        "        1. Hapus Data Pasien\n",
        "        2. Kembali ke Menu Utama\n",
        "        \n",
        "        Silahkan Masukkan Pilihan Menu : '''))\n",
        "        print()\n",
        "        if pilihanMenghapusData == 1:\n",
        "            IDPasien = int(input(\"Masukkan ID Pasien Yang Ingin Di Hapus : \"))\n",
        "            i = getIndexByID(IDPasien)\n",
        "            if(i != -1):\n",
        "                print('IDPasien\\t|Nama Pasien\\t|Jenis Kelamin\\t| Usia Pasien\\t| Penyakit\\t| Poli\\t\\t| Biaya Pengobatan')\n",
        "                print('{}\\t\\t|{}\\t\\t|{}\\t\\t| {}\\t\\t| {}\\t\\t| {}\\t\\t| {}\\t'.format(ListPasienRumahSakit[i].get('IDPasien'),ListPasienRumahSakit[i].get('Nama Pasien'),ListPasienRumahSakit[i].get('Jenis Kelamin'),ListPasienRumahSakit[i].get('Usia Pasien'),ListPasienRumahSakit[i].get('Penyakit'),ListPasienRumahSakit[i].get('Poli'),ListPasienRumahSakit[i].get('Biaya Pengobatan')))\n",
        "                YakinMenghapusData = input(\"Apakah Anda Yakin Ingin Menghapus Data Pasien? (Y/N)\")\n",
        "                print()\n",
        "                if YakinMenghapusData.casefold() == 'Y'.casefold():\n",
        "                    print(\"Data Pasien Berhasil Dihapus\")\n",
        "                    del ListPasienRumahSakit[i]\n",
        "                    break\n",
        "                elif YakinMenghapusData.casefold() == 'N'.casefold():\n",
        "                    print(\"Data Batal Untuk Dihapus\")\n",
        "                    break\n",
        "                else:\n",
        "                    print(\"Silahkan Ketik 'Y' Jika Ingin Melanjutkan Penghapusan Data atau 'N' Jika Ingin Membatalkan Penghapusan Data\")\n",
        "            else:\n",
        "                print()\n",
        "                print(\"Pasien Yang Anda Cari Tidak Ada\")\n",
        "                break\n",
        "\n",
        "        elif pilihanMenghapusData == 2:\n",
        "            inginKembali = input(\"Apakah Anda Ingin Kembali ke Menu Utama? (Y/N) : \")\n",
        "            if inginKembali.casefold() == 'Y'.casefold():\n",
        "                break\n",
        "            elif inginKembali.casefold() == 'N'.casefold():\n",
        "                continue\n",
        "            else:\n",
        "                print(\"Silahkan Ketik 'Y' Jika Ingin Kembali ke Menu Utama atau Ketik 'N' Jika Ingin Tetap di Menu Mengubah Data Pasien\")\n",
        "                continue\n",
        "        else:\n",
        "            print(\"Maaf, Menu yang Anda pilih tidak tersedia. Silahkan Memilih Menu yang lain\")\n",
        "\n",
        "#Menu Transaksi Pengobatan\n",
        "def MembayarBiayaPengobatan():\n",
        "    TampilkanListSemuaDataPasien()\n",
        "    while True :\n",
        "        IDPasien = int(input('Masukkan ID pasien: '))\n",
        "        indexPasien = getIndexByID(IDPasien)\n",
        "        if(indexPasien != -1) :\n",
        "            print('IDPasien\\t|Nama Pasien\\t|Jenis Kelamin\\t| Usia Pasien\\t| Penyakit\\t| Poli\\t\\t| Biaya Pengobatan')\n",
        "            print('{}\\t\\t|{}\\t\\t|{}\\t\\t| {}\\t\\t| {}\\t\\t| {}\\t\\t| {}\\t'.format(ListPasienRumahSakit[indexPasien].get('IDPasien'),ListPasienRumahSakit[indexPasien].get('Nama Pasien'),ListPasienRumahSakit[indexPasien].get('Jenis Kelamin'),ListPasienRumahSakit[indexPasien].get('Usia Pasien'),ListPasienRumahSakit[indexPasien].get('Penyakit'),ListPasienRumahSakit[indexPasien].get('Poli'),ListPasienRumahSakit[indexPasien].get('Biaya Pengobatan')))\n",
        "            break\n",
        "        else :\n",
        "            print('ID Pasien Tidak Ditemukan!')\n",
        "            checker = input('Ingin membayar yang lain? (Y/N) = ')\n",
        "            if checker.casefold() == 'N'.casefold() :\n",
        "                break\n",
        "\n",
        "    print('Daftar Biaya Pengobatan: ')\n",
        "    print('IDPasien\\t|Nama Pasien\\t|Jenis Kelamin\\t| Usia Pasien\\t| Penyakit\\t| Poli\\t\\t| Biaya Pengobatan')\n",
        "    print('{}\\t\\t|{}\\t\\t|{}\\t\\t| {}\\t\\t| {}\\t\\t| {}\\t\\t| {}\\t'.format(ListPasienRumahSakit[indexPasien].get('IDPasien'),ListPasienRumahSakit[indexPasien].get('Nama Pasien'),ListPasienRumahSakit[indexPasien].get('Jenis Kelamin'),ListPasienRumahSakit[indexPasien].get('Usia Pasien'),ListPasienRumahSakit[indexPasien].get('Penyakit'),ListPasienRumahSakit[indexPasien].get('Poli'),ListPasienRumahSakit[indexPasien].get('Biaya Pengobatan')))\n",
        "    \n",
        "\n",
        "    BIAYAPENGOBATAN = ListPasienRumahSakit[indexPasien].get('Biaya Pengobatan')\n",
        "\n",
        "    while True :\n",
        "        print('Total Yang Harus Dibayar = Rp.{}'.format(BIAYAPENGOBATAN))\n",
        "        jmlUang = int(input('Masukkan Jumlah Uang : '))\n",
        "        NAMAPASIEN = input('Masukkan Nama Anda : ')\n",
        "        if(jmlUang >= BIAYAPENGOBATAN) :\n",
        "            Kembalian = jmlUang - BIAYAPENGOBATAN\n",
        "\n",
        "            if(Kembalian > 0):\n",
        "                print('Terima kasih {} \\n\\nUang kembali anda sebesar : {}'.format(NAMAPASIEN, Kembalian))\n",
        "            else:\n",
        "                print('Terima kasih {}'.format(NAMAPASIEN))\n",
        "            del ListPasienRumahSakit[indexPasien]\n",
        "            break\n",
        "        else :\n",
        "            Kekurangan = BIAYAPENGOBATAN - jmlUang\n",
        "            print('Maaf {}, Uang Anda Kurang Sebesar: {}'.format(NAMAPASIEN, Kekurangan))\n",
        "\n",
        "#function untuk update data\n",
        "def UpdateData(key, id:int, value):\n",
        "    for i, k in enumerate(list(ListPasienRumahSakit[0].keys())):\n",
        "        if(str(key).strip().casefold() == k.strip().casefold()):\n",
        "            newValue = {k:value}\n",
        "            ListPasienRumahSakit[id].update(newValue)\n",
        "            break\n",
        "\n",
        "#function untuk cek apakah id unique\n",
        "def isUniqueId(id):\n",
        "    for i in range(len(ListPasienRumahSakit)):\n",
        "        if(ListPasienRumahSakit[i].get('IDPasien') == id):\n",
        "            return False\n",
        "    return True\n",
        "        \n",
        "# mencari index dengan id yang diberikan\n",
        "def getIndexByID(id):\n",
        "    for i in range(len(ListPasienRumahSakit)):\n",
        "        if(ListPasienRumahSakit[i].get('IDPasien') == id):\n",
        "            return i\n",
        "    return -1\n",
        "\n",
        "\n",
        "def main():\n",
        "    global runProgram\n",
        "    PilihanMenuUtama = input('''\n",
        "    Selamat Datang di Rumah Sakit Brawijaya\n",
        "    \n",
        "    1. Lihat Data Pasien Rumah Sakit\n",
        "    2. Menambahkan Data Pasien Rumah Sakit\n",
        "    3. Mengubah Data Pasien\n",
        "    4. Menghapus Data Pasien\n",
        "    5. Melakukan Transaksi Pengobatan\n",
        "    6. Exit Program\n",
        "    \n",
        "    Masukkan Pilihan Menu Utama : ''')\n",
        "    if PilihanMenuUtama == '1' :\n",
        "        MenampilkanListPasienRumahSakit()\n",
        "    elif PilihanMenuUtama == '2' :\n",
        "        MenambahkanDataPasienRumahSakit()\n",
        "    elif PilihanMenuUtama == '3' :\n",
        "        MengubahDataPasien()\n",
        "    elif PilihanMenuUtama == '4' :\n",
        "        MenghapusDataPasien()\n",
        "    elif PilihanMenuUtama == '5' :\n",
        "        MembayarBiayaPengobatan()\n",
        "    elif PilihanMenuUtama == '6' :\n",
        "        print('Program Berhenti Untuk Dijalankan')\n",
        "        runProgram = False\n",
        "    else :\n",
        "        print('Maaf, Menu Yang Dipilih Tidak Ada. Silahkan Pilih Menu Utama Yang Tersedia')\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    runProgram = True\n",
        "    while(runProgram):\n",
        "        main()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "VBNmyohurGiU"
      },
      "outputs": [],
      "source": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "T8np1BEwrGiV"
      },
      "outputs": [],
      "source": []
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.10.8"
    },
    "orig_nbformat": 4,
    "vscode": {
      "interpreter": {
        "hash": "5cdb6cce9ff7683689e83e5e737510fc752bb50cf50c0095215669f6dc0d3a12"
      }
    },
    "colab": {
      "provenance": []
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}